config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  post '/leave_message' => 'main#leave_message'

  get 'main_webapp/index'
  get 'dashboard' => 'main_webapp#dashboard'
  get 'evangelio' => 'main_webapp#evangelio'
  get 'staff'     => 'main_webapp#staff'

  devise_for :users

  resources :semesters do
    member do
      post 'current'
    end
  end
  resources :group_enrollments
  resources :group_offerings do
    collection do
      get 'lectures'
      get 'workshops'
      get 'commissions'
      get 'shepperdings'
    end
  end
  resources :child_semesters do
    member do
      delete 'sweet_destroy'
    end
    collection do
      get 'current'
    end
    member do
      get 'receipt'
      put 'pay'
      put 'unpay'
    end
  end
  resources :coordinator_semesters do
    collection do
      get 'current'
    end
  end

  resources :notifications do
    collection do
      get 'read'
      post 'mark_as_read'
    end
  end
  resources :notices do
    collection do
      get 'view'
    end
  end
  resources :users do
    member do
      post 'assign_to_workshop'
      post 'assign_to_shepperding'
      post 'assign_to_lecture'
      post 'assign_to_commission'
      post 'assign_child'
      delete 'unassign_from_workshop'
      delete 'unassign_from_shepperding'
      delete 'unassign_from_lecture'
      delete 'unassign_from_commission'
      delete 'unassign_child'
      post 'assign_child'
      delete 'unassign_child'
      delete 'unshare_task'
      post 'toggle_sidebar'
      post 'add_email'
      post 'add_phone'
      get 'edit_tutor'
      get 'edit_coordinator'
      get 'show_tutor'
      get 'show_coordinator'
    end
    collection do
      get 'tutors'
      get 'coordinators'
      get 'new_coordinator'
      get 'new_tutor'
      get 'typeaheaddata'
      get 'profile'
      patch 'update_password'
      patch 'update_profile'
    end
  end
  resources :emails
  resources :phones
  resources :events do
    collection do
      get 'edit_all'
    end
  end
  resources :workshops do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
      post 'enroll_child'
      delete 'unenroll_child'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :lectures do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
      post 'enroll_child'
      delete 'unenroll_child'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :children do
    member do
      post 'assign_to_tutor'
      delete 'unassign_from_tutor'
      post 'enroll_in_workshop'
      post 'enroll_in_lecture'
      post 'enroll_in_shepperding'
      delete 'unenroll_from_workshop'
      delete 'unenroll_from_lecture'
      delete 'unenroll_from_shepperding'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :visitor_messages
  resources :shepperdings do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
      post 'enroll_child'
      delete 'unenroll_child'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :commissions do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :tasks do
    member do
      post 'assign_to_coordinator'
      delete 'unassign_from_coordinator'
      post 'share_to_coordinator'
      post 'mark_as_completed'
      delete 'unmark_as_completed'
    end
  end
  resources :projects do
    member do
      post 'assign_to_coordinator'
      delete 'unassign_from_coordinator'
      post 'share_to_coordinator'
      post 'mark_as_completed'
      delete 'unmark_as_completed'
    end
  end

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
	attachment :image, type: :image
	acts_as_marker

  has_many :group_offerings, as: :group

  def children_enrolled_on_semester( semester )
    gos = group_offerings.find_by_semester_id( semester.id )
    if gos
      gos.group_enrollments.where( enrolled_type: 'Child' )
    else
      []
    end
  end

  def coordinators_enrolled_on_semester( semester )
    gos = group_offerings.find_by_semester_id( semester.id )
    if gos
      gos.group_enrollments.where( enrolled_type: 'User')
    else
      []
    end
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < WebApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy, :assign_coordinator, :unassign_coordinator, :enroll_child, :unenroll_child]

  # GET /workshops
  # GET /workshops.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: WorkshopDatatable.new(view_context) }
    end
  end

  # GET /workshops/typeaheaddata.json
  def typeaheaddata
    render json: Workshop.select(:id, :name), status: 200
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    RecentItem.create( visitor: current_user, recentable: @workshop )
    @semester = ( params['semester'] == nil ? @current_semester : Semester.find( params['semester'] ) )
    @group_enrollment = GroupEnrollment.new
    @group_offering = @workshop.group_offerings.find_by_semester_id( @semester.id )
  end

  # POST /workshops/1/assign_coordinator
  def assign_coordinator
    if @workshop.set_mark :coordinator_workshop, User.find(params[:coordinator_id])
      redirect_to @workshop, notice: 'Coordinator successfully assigned'
    else
      redirect_to @workshops, alert: 'Could not assign coordinator'
    end
  end

  # DELETE /workshops/1/unassign_coordinator
  def unassign_coordinator
    if @workshop.remove_mark :coordinator_workshop, User.find(params[:coordinator_id])
      redirect_to @workshop, notice: 'Coordinator successfully unassigned'
    else
      redirect_to @workshops, alert: 'Could not unassign coordinator'
    end
  end

  # POST /workshops/1/enroll_child
  def enroll_child
    if @workshop.set_mark :enrolled_workshop, Child.find(params[:child_id])
      redirect_to @workshop, notice: 'Child successfully enrolled'
    else
      redirect_to @workshops, alert: 'Could not enroll child'
    end
  end

  # DELETE /workshops/1/unenroll_child
  def unenroll_child
    if @workshop.remove_mark :enrolled_workshop, Child.find(params[:child_id])
      redirect_to @workshop, notice: 'Child successfully unenrolled'
    else
      redirect_to @workshops, alert: 'Could not unenroll child'
    end
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:name, :description, :image)
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_assign_child_form.html.erb
<%= form_tag enroll_child_workshop_path, method: :post do %>
  <%= hidden_field_tag :child_id %>
  <div class='input-group'>
    <%= text_field_tag :child, nil, placeholder: 'Niño', class: 'form-control ticnsp-form-control', id: 'children-typeahead', autocomplete: 'off' %>
    <span class='input-group-btn'>
      <button class='btn bg-blue btn-flat' type='submit'><i class='fa fa-pencil-square-o'></i> Asignar</button>
    </span>
    <script>
    	$(function () {
    		$.getJSON('/children/typeaheaddata', function (data) {
    			$('#children-typeahead').typeahead({
	    			source: data,
	    			scrollBar: true,
	    			onSelect: function (item) {
	    				$('#child_id').val(item.value);
	    			}
	    		});
    		});
    	});
    </script>
  </div>
<% end %>

app/views/workshops/_assign_coordinator_form.html.erb
<%= form_tag assign_coordinator_workshop_path, method: :post do %>
  <%= hidden_field_tag :coordinator_id %>
  <div class='input-group'>
    <%= text_field_tag :coordinator, nil, placeholder: 'Coordinador', class: 'form-control ticnsp-form-control', id: 'coordinators-typeahead', autocomplete: 'off' %>
    <span class='input-group-btn'>
      <button class='btn bg-green btn-flat' type='submit'><i class='fa fa-pencil-square-o'></i> Asignar</button>
    </span>
    <script>
    	$(function () {
    		$.getJSON('/users/typeaheaddata', { usertype: 'coordinator' }, function (data) {
    			$('#coordinators-typeahead').typeahead({
	    			source: data,
	    			scrollBar: true,
	    			onSelect: function (item) {
	    				$('#coordinator_id').val(item.value);
	    			}
	    		});
    		});
    	});
    </script>
  </div>
<% end %>

app/views/workshops/_form.html.erb
<%= form_for(@workshop, html: { class: 'form-horizontal' }) do |f| %>
  <% if @workshop.errors.any? %>
    <div id="error_explanation" class='alert alert-danger'>
      <strong><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</strong>

      <ul>
      <% @workshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <hr>
  <div class="form-group">
    <%= f.label 'Nombre', class: 'col-sm-2 control-label' %>
    <div class='col-sm-9'>
      <%= f.text_field :name, class: 'form-control form-control-ticnsp' %>
    </div>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label 'Descripción', class: 'col-sm-2 control-label' %>
    <div class='col-sm-9'>
      <%= f.text_field :description, class: 'form-control form-control-ticnsp' %>
    </div>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label 'Imagen', class: 'col-sm-2 control-label' %>
    <div class='col-sm-9'>
      <span class='file-input'>
        Browse<%= f.attachment_field :image, class: '' %>
      </span>
      <span class="filename"></span>
    </div>
  </div>
  <hr>
  <div class="form-group">
    <div class='col-sm-offset-2 col-sm-2'>
      <%= f.submit 'Guardar', class: 'btn btn-ticnsp' %>
    </div>
  </div>

<% end %>

app/views/workshops/edit.html.erb
<% content_for :title, 'Taller - TIC' %>
<% content_for :page_title, 'Editar taller' %>
<% content_for :page_breadcrumb, "<li>#{ link_to '<span class="fa fa-dashboard"></span> Dashboard'.html_safe, root_path }</li><li>#{ link_to 'Talleres', workshops_path }</li><li>Editar taller</li>".html_safe %>
<div class='box box-solid'>
	<div class='box-header with-border'>
		<h3 class='box-title'>Favor de llenar la información</h3>
	</div>
	<div class='box-body'>
		<%= link_to '<i class="fa fa-mail-reply"></i> Back'.html_safe, workshops_path, class: 'btn btn-app' %>
		<%= link_to '<i class="fa fa-search-plus"></i> Show'.html_safe, @workshop, class: 'btn btn-app' %>
	</div>
	<div class='box-body'>
		<%= render 'form' %>
	</div>
</div>

app/views/workshops/index.html.erb
<% content_for :title, 'Talleres - TIC' %>
<% content_for :page_title, 'Talleres' %>
<% content_for :page_breadcrumb, "<li>#{ link_to '<span class="fa fa-dashboard"></span> Dashboard'.html_safe, root_path }</li><li>Talleres</li>".html_safe %>

<div class='box box-solid'>
  <div class='box-header with-border'>
    <h3 class='box-title'>Acciones</h3>
  </div>
  <div class='box-body'>
    <%= link_to '<i class="fa fa-plus"></i> Crear'.html_safe, new_workshop_path, class: 'btn btn-app' %>
  </div>
</div>

<div class='box box-solid'>
  <div class='container-fluid table-responsive'>
    <table class='table table-bordered table-hover dataTable responsive no-wrap' id='workshops-table', data-source="<%= workshops_path(format: :json) %>">
      <br>
      <thead>
        <tr>
          <th>ID</th>
          <th>Nombre</th>
          <th>Descripción</th>
        </tr>
      </thead>
    </table>
  </div>
</div>

app/views/workshops/new.html.erb
<% content_for :title, 'Taller - TIC' %>
<% content_for :page_title, 'Crear taller' %>
<% content_for :page_breadcrumb, "<li>#{ link_to '<span class="fa fa-dashboard"></span> Dashboard'.html_safe, root_path }</li><li>#{ link_to 'Taller', workshops_path }</li><li>Crear taller</li>".html_safe %>
<div class='box box-solid'>
	<div class='box-header with-border'>
		<h3 class='box-title'>Favor de llenar la información</h3>
	</div>
	<div class='box-body'>
		<%= link_to '<i class="fa fa-mail-reply"></i> Back'.html_safe, workshops_path, class: 'btn btn-app' %>
	</div>
	<div class='box-body'>
		<%= render 'form' %>
	</div>
</div>

app/views/workshops/show.html.erb
<% content_for :title, 'Talleres - TIC' %>
<% content_for :page_title, 'Detalles de taller' %>
<% content_for :page_breadcrumb, "<li>#{ link_to '<span class="fa fa-dashboard"></span> Dashboard'.html_safe, root_path }</li><li>#{ link_to 'Talleres', workshops_path }</li>".html_safe %>

<div class='row'>
  <div class='col-lg-3'>
    <!-- Mainbox -->
    <div class='box box-primary'>
      <div class='box-body'>
        <%= image_tag attachment_url(@workshop, :image), class: 'profile-user-img img-responsive img-circle' %>
        <h3 class='profile-username text-center'><%= @workshop.name %></h3>
        <p class='text-muted text-center'>Taller</p>
        <ul class='list-group list-group-unbordered'>
          <li class='list-group-item'>
            <b>Niños inscritos</b>
            <span class='pull-right'><%= @workshop.children_enrolled_on_semester( @semester ).count %></span>
          </li>
          <li class='list-group-item'>
            <b>Coordinadores inscritos</b>
            <span class='pull-right'><%= @workshop.coordinators_enrolled_on_semester( @semester ).count %></span>
          </li>
        </ul>
        <% if ['admin', 'general_coordinator'].include? current_user.usertype %>
          <%= link_to '<i class="fa fa-pencil"></i> Editar'.html_safe, edit_workshop_path( @workshop ), class: 'btn btn-default' %>
        <% end %>
        <% if current_user.usertype =~ /admin/ %>
          <%= link_to '<i class="fa fa-times"></i> Eliminar'.html_safe, @workshop, class: 'btn bg-maroon pull-right', method: :delete, 'data-confirm' => 'Are you sure?' %>
        <% end %>
      </div>
    </div>

    <!-- About box -->
    <div class='box box-primary'>
      <div class='box-header with-border'>
        <h3 class='box-title'>Información</h3>
      </div>
      <div class='box-body'>
        <strong><i class='fa fa-list'></i> Descripción</strong>
        <p class='text-muted'><%= @workshop.description %></p>
        <hr>
      </div>
    </div>

  </div>
  <div class='col-lg-9'>
    <div class='nav-tabs-custom'>
      <ul class='nav nav-tabs'>
        <li class='active'><a href='#workshop-enrollment-children' data-toggle='tab'>Niños</a></li>
        <li><a href='#workshop-enrollment-coordinators' data-toggle='tab'>Coordinadores</a></li>
      </ul>
      <div class='tab-content'>
        <div class='tab-pane active' id='workshop-enrollment-children'>
          <div class='row'>
            <div class='col-xs-12'>
              <%= form_for( @group_enrollment, html: { class: 'form-inline pull-left' } ) do |f| %>
                <%= f.hidden_field :group_offering_id, value: @group_offering.id if @group_offering %>
                <%= f.hidden_field :enrolled_type, value: 'Child' %>
                <%= f.hidden_field :enrolled_id, id: 'child_enrolled_id' %>
                <fieldset <%= "disabled" unless @group_offering %>>
                  <div class='input-group'>
                    <%= text_field_tag :child, nil, placeholder: 'Nombre', id: 'children-typeahead', class: 'form-control', autocomplete: 'off' %>
                    <span class="input-group-btn">
                      <%= f.submit 'Inscribir niño', class: 'btn btn-default btn-flat' %>
                    </span>
                    <script>
                      $(function () {
                        $.getJSON('/child_semesters/current', function (data) {
                          $('#children-typeahead').typeahead({
                            source: data,
                            scrollBar: true,
                            onSelect: function (item) {
                              $('#child_enrolled_id').val(item.value);
                            }
                          });
                        });
                      });
                    </script>
                  </div>
                </fieldset>
                <% if @group_enrollment.errors.any? %>
                  <div class="alert alert-danger">
                    <strong><%= pluralize(@group_enrollment.errors.count, "error") %> prohibited this article from being saved:</strong>
                    <ul>
                      <% @group_enrollment.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
              <% end %>
              <%= form_tag workshop_path( @workshop ), method: :get, class: 'form-inline pull-right' do %>
                <%= select_tag :semester, options_from_collection_for_select( Semester.current_first, 'id', 'name', @semester.id ), class: 'form-control', onchange: 'this.form.submit();' %>
              <% end %>
            </div>
          </div>
          <br>
          <div class='row'>
            <div class='col-xs-12'>
              <% @workshop.children_enrolled_on_semester( @semester ).each do |child_enrollment| %>
                <%= link_to child_enrollment.enrolled.full_name, child_enrollment.enrolled %>
                <%= link_to "<i class='fa fa-times'></i>".html_safe, child_enrollment, method: :delete, class: 'btn btn-danger pull-right', data: { confirm: 'Are you sure?' } %>
                <hr>
              <% end %>
            </div>
          </div>
        </div>
        <div class='tab-pane' id='workshop-enrollment-coordinators'>
          <div class='row'>
            <div class='col-xs-12'>
              <%= form_for( @group_enrollment, html: { class: 'form-inline pull-left' } ) do |f| %>
                <%= f.hidden_field :group_offering_id, value: @group_offering.id if @group_offering %>
                <%= f.hidden_field :enrolled_type, value: 'User' %>
                <%= f.hidden_field :enrolled_id, id: 'coordinator_enrolled_id' %>
                <fieldset <%= "disabled" unless @group_offering %>>
                  <div class='input-group'>
                    <%= text_field_tag :coordinator, nil, placeholder: 'Nombre', id: 'coordinator-typeahead', class: 'form-control', autocomplete: 'off' %>
                    <span class="input-group-btn">
                      <%= f.submit 'Inscribir coordinador', class: 'btn btn-default btn-flat' %>
                    </span>
                    <script>
                      $(function () {
                        $.getJSON('/coordinator_semesters/current', function (data) {
                          $('#coordinator-typeahead').typeahead({
                            source: data,
                            scrollBar: true,
                            onSelect: function (item) {
                              $('#coordinator_enrolled_id').val(item.value);
                            }
                          });
                        });
                      });
                    </script>
                  </div>
                </fieldset>
              <% end %>
              <%= form_tag workshop_path( @workshop ), method: :get, class: 'form-inline pull-right' do %>
                <%= select_tag :semester, options_from_collection_for_select( Semester.current_first, 'id', 'name', @semester.id ), class: 'form-control', onchange: 'this.form.submit();' %>
              <% end %>
            </div>
          </div>
          <br>
          <div class='row'>
            <div class='col-xs-12'>
              <% @workshop.coordinators_enrolled_on_semester( @semester ).each do |coordinator_enrollment| %>
                <%= link_to coordinator_enrollment.enrolled.full_name, coordinator_enrollment.enrolled %>
                <%= link_to "<i class='fa fa-times'></i>".html_safe, coordinator_enrollment, method: :delete, class: 'btn btn-danger pull-right', data: { confirm: 'Are you sure?' } %>
                <hr>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>