config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  post '/leave_message' => 'main#leave_message'

  get 'main_webapp/index'
  get 'dashboard' => 'main_webapp#dashboard'
  get 'evangelio' => 'main_webapp#evangelio'
  get 'staff'     => 'main_webapp#staff'

  devise_for :users

  resources :semesters do
    member do
      post 'current'
    end
  end
  resources :group_enrollments
  resources :group_offerings do
    collection do
      get 'lectures'
      get 'workshops'
      get 'commissions'
      get 'shepperdings'
    end
  end
  resources :child_semesters do
    member do
      delete 'sweet_destroy'
    end
    collection do
      get 'current'
    end
    member do
      get 'receipt'
      put 'pay'
      put 'unpay'
    end
  end
  resources :coordinator_semesters do
    collection do
      get 'current'
    end
  end

  resources :notifications do
    collection do
      get 'read'
      post 'mark_as_read'
    end
  end
  resources :notices do
    collection do
      get 'view'
    end
  end
  resources :users do
    member do
      post 'assign_to_workshop'
      post 'assign_to_shepperding'
      post 'assign_to_lecture'
      post 'assign_to_commission'
      post 'assign_child'
      delete 'unassign_from_workshop'
      delete 'unassign_from_shepperding'
      delete 'unassign_from_lecture'
      delete 'unassign_from_commission'
      delete 'unassign_child'
      post 'assign_child'
      delete 'unassign_child'
      delete 'unshare_task'
      post 'toggle_sidebar'
      post 'add_email'
      post 'add_phone'
      get 'edit_tutor'
      get 'edit_coordinator'
      get 'show_tutor'
      get 'show_coordinator'
    end
    collection do
      get 'tutors'
      get 'coordinators'
      get 'new_coordinator'
      get 'new_tutor'
      get 'typeaheaddata'
      get 'profile'
      patch 'update_password'
      patch 'update_profile'
    end
  end
  resources :emails
  resources :phones
  resources :events do
    collection do
      get 'edit_all'
    end
  end
  resources :workshops do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
      post 'enroll_child'
      delete 'unenroll_child'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :lectures do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
      post 'enroll_child'
      delete 'unenroll_child'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :children do
    member do
      post 'assign_to_tutor'
      delete 'unassign_from_tutor'
      post 'enroll_in_workshop'
      post 'enroll_in_lecture'
      post 'enroll_in_shepperding'
      delete 'unenroll_from_workshop'
      delete 'unenroll_from_lecture'
      delete 'unenroll_from_shepperding'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :visitor_messages
  resources :shepperdings do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
      post 'enroll_child'
      delete 'unenroll_child'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :commissions do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :tasks do
    member do
      post 'assign_to_coordinator'
      delete 'unassign_from_coordinator'
      post 'share_to_coordinator'
      post 'mark_as_completed'
      delete 'unmark_as_completed'
    end
  end
  resources :projects do
    member do
      post 'assign_to_coordinator'
      delete 'unassign_from_coordinator'
      post 'share_to_coordinator'
      post 'mark_as_completed'
      delete 'unmark_as_completed'
    end
  end

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :user

	def text_stripped
		Nokogiri::HTML(text).xpath("//text()").to_s
	end

  def notice_type_color
    case notice_type
    when 'info'
      'teal'
    when 'warning'
      'orange'
    when 'success'
      'green'
    when 'danger'
      'red'
    end
  end
end

app/controllers/notices_controller.rb
class NoticesController < WebApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    # Select the notices depending on audience and usertype
    if current_user.usertype =~ /admin/
      @notices = Notice.includes( :user ).order( created_at: :desc ).paginate(page: params[:page], per_page: 5)
    elsif current_user.usertype =~ /coordinator$/
      @notices = Notice.includes( :user ).where( audicence: 'coordinators' ).order( created_at: :desc ).paginate( page: params[:page], per_page: 5 )
    elsif current_user.usertype =~ /^tutor$/
      @notices = Notice.includes( :user ).where( audience: 'tutors' ).order( created_at: :desc ).paginate( page: params[:page], per_page: 5 )
    end
  end

  # GET /notices/view
  def view
    @notices = Notice.includes( :user ).order( created_at: :desc ).paginate(page: params[:page], per_page: 5)
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)
    @notice.user = current_user

    respond_to do |format|
      if @notice.save

        # Create a notifition when a notice is created
        users_to_notify = []
        case @notice.audience
        when 'coordinators'
          users_to_notify = User.active_coordinators + User.where(usertype: 'general_coordinator')
        when 'tutors'
          users_to_notify = User.tutors + User.where( usertype: 'admin' )
        when 'all'
          users_to_notify = User.where( active: true )
        else
          # nothing to do here ...here
        end

        users_to_notify.each do |user|
          notification = Notification.create( recipient: user, actor: current_user, action: 'publicó', notifiable: @notice )

          # Create send notification by email background job
          NoticeEmailJob.new.async.perform( user, @notice )
        end

        # Send Twilio SMS (use the subject field)

        format.html { redirect_to notices_url( anchor: "notice_#{ @notice.id }" ), notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:heading, :text, :audience, :notice_type)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
  def notice_author( author )
    if author.usertype =~ /admin/
      "Administrador"
    else
      author.full_name
    end
  end
end

app/views/notices/_form.html.erb
<%= form_for(@notice, html: { class: 'form-horizontal' }) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <strong><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</strong>

      <ul>
      <% @notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <hr>
  <div class="form-group">
    <%= f.label 'Título', class: 'control-label col-sm-2' %>
    <div class='col-sm-9'>
      <%= f.text_field :heading, class: 'form-control' %>
    </div>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label 'Mensaje', class: 'control-label col-sm-2' %>
    <div class='col-sm-9'>
      <%= f.text_area :text, class: 'form-control', style: 'height: 200px;' %>
    </div>
    <script>
      $(document).ready(function () {
        $('#notice_text').wysihtml5();
      });
    </script>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label 'Público', class: 'control-label col-sm-2' %>
    <div class='col-sm-3'>
      <%= f.select :audience, options_for_select([['Coordinadores','coordinators'],['Tutores','tutors'],['Todos','all']], selected: @notice.audience), {}, {class: "form-control"} %>
    </div>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label 'Tipo', class: 'control-label col-sm-2' %>
    <div class='col-sm-3'>
      <%= f.select :notice_type, options_for_select([['Información','info'],['Buena noticia','success'],['Atención','warning'],['Urgente','danger']], selected: @notice.notice_type), {}, {class: "form-control"} %>
    </div>
  </div>
  <hr>
  <div class="form-group">
    <div class='col-sm-offset-2 col-sm-3'>
      <%= f.submit 'Publicar aviso', class: 'btn btn-info' %>
    </div>
  </div>
<% end %>

app/views/notices/_notice.html.erb
<div class='box box-widget' id='<%= dom_id notice %>'>
  <div class='box-header with-border'>
    <div class='user-block'>
      <%= image_tag notice.user.current_image(128), class: 'img-circle', alt: 'User Image' %>
      <span class='username'>
        <%= link_to notice_author( notice.user ), user_path(id: notice.user_id) %>
      </span>
      <span class='description'>Publicado <%= notice.created_at.strftime( '%b %d, %Y %H:%M' ) %></span>
    </div>
    <div class='box-tools'>
      <%= (link_to "<i class='fa fa-times'></i>".html_safe, notice, class: 'btn btn-box-tools', method: :delete, 'data-confirm' => "¿Seguro que deseas borrar este aviso?") if ['general_coordinator', 'admin'].include? current_user.usertype %>
    </div>
  </div>
  <div class='box-body'>
    <%= notice.text.html_safe %>
  </div>
</div>

app/views/notices/edit.html.erb
<% content_for :title, 'Avisos - TIC' %>
<% content_for :page_title, 'Editar aviso' %>
<% content_for :page_breadcrumb, "<li>#{ link_to 'Avisos', notices_path }</li><li>Editar aviso</li>".html_safe %>

<div class='row'>
	<div class='col-xs-12'>
		<div class='box box-solid'>
			<div class='box-header with-border'>
				<h3 class='box-title'>Editor de texto</h3>
			</div>
			<div class='box-body'>
				<%= link_to '<i class="fa fa-mail-reply"></i> Atrás'.html_safe, notices_path, class: 'btn btn-app' %>
				<%= link_to '<i class="fa fa-search-plus"></i> Mostrar'.html_safe, @notice, class: 'btn btn-app' %>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/notices/index.html.erb
<% content_for :title, 'Avisos - TIC' %>
<% content_for :page_title, 'Avisos' %>
<% content_for :page_breadcrumb, '<li>Avisos</li>'.html_safe %>

<% if ['general_coordinator', 'admin'].include? current_user.usertype %>
  <div class='row'>
    <div class='col-xs-12'>
      <div class='box box-solid'>
        <div class='box-header with-border'>
          <h3 class='box-title'>Acciones</h3>
        </div>
        <div class='box-body'>
          <%= link_to '<i class="fa fa-pencil-square-o"></i> Nuevo aviso'.html_safe, new_notice_path, class: 'btn btn-app' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class='row'>
	<div class='col-xs-12'>
    <% @notices.each do |notice| %>
      <%= render 'notices/notice', notice: notice %>
		<% end %>
		<%= will_paginate @notices, renderer: BootstrapPagination::Rails %>
	</div>
</div>

app/views/notices/new.html.erb
<% content_for :title, 'Avisos - TIC' %>
<% content_for :page_title, 'Nuevo avisos' %>
<% content_for :page_breadcrumb, "<li>#{ link_to 'Avisos', notices_path }</li><li>Nuevo aviso</li>".html_safe %>

<div class='row'>
	<div class='col-xs-12'>
		<div class='box box-solid'>
			<div class='box-header with-border'>
				<h3 class='box-title'>Editor de texto</h3>
			</div>
			<div class='box-body'>
				<%= link_to '<i class="fa fa-mail-reply"></i> Atrás'.html_safe, notices_path, class: 'btn btn-app' %>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/notices/show.html.erb
<% content_for :title, 'Avisos - TIC' %>
<% content_for :page_title, 'Detalle de aviso' %>
<% content_for :page_breadcrumb, "<li>#{ link_to 'Avisos', notices_path }</li><li>Detalles de aviso</li>".html_safe %>

<div class='box box-solid'>
	<div class='box-header with-border'>
		<h3 class='box-title'>Acciones</h3>
	</div>
	<div class='box-body'>
		<%= link_to '<i class="fa fa-mail-reply"></i> Atrás'.html_safe, notices_path, class: 'btn btn-app' %>
		<%= link_to '<i class="fa fa-pencil"></i> Editar'.html_safe, edit_notice_path(@notice), class: 'btn btn-app' %>
	</div>
</div>

<div class='box box-solid'>
	<div class='box-body'>
		<hr>
		<h4 class='text-<%= @notice.notice_type%>'><%= @notice.heading %></h4>
		<span class='text-muted'>Publicado <%= @notice.created_at.strftime(' %b %d, %Y %H:%M') %></span>
		<p><%= @notice.text.html_safe %></p>
		<hr>
	</div>
</div>

app/views/notices/view.html.erb
<% content_for :title, 'Avisos - TIC' %>
<% content_for :page_title, 'Avisos' %>
<% content_for :page_breadcrumb, "<li>#{ link_to '<i class="fa fa-dashboard"></i>Dashboard'.html_safe, dashboard_path }</li><li>Avisos</li>".html_safe %>

<div class='row'>
	<div class='col-xs-12'>
		<div class='box box-solid'>
			<div class='box-header with-border'>
				<h3 class='box-title'>Acciones</h3>
			</div>
			<div class='box-body'>
				<%= link_to '<i class="fa fa-pencil-square-o"></i> Administrar avisos'.html_safe, notices_path, class: 'btn btn-app' %>
			</div>
		</div>
	</div>
</div>
<br />
<div class='row'>
	<div class='col-xs-12'>
		<%= will_paginate @notices, renderer: BootstrapPagination::Rails %>
    <% @notices.each do |notice| %>
      <%= render 'notices/notice', notice: notice %>
		<% end %>
		<%= will_paginate @notices, renderer: BootstrapPagination::Rails %>
	</div>
</div>