config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  post '/leave_message' => 'main#leave_message'

  get 'main_webapp/index'
  get 'dashboard' => 'main_webapp#dashboard'
  get 'evangelio' => 'main_webapp#evangelio'
  get 'staff'     => 'main_webapp#staff'

  devise_for :users

  resources :semesters do
    member do
      post 'current'
    end
  end
  resources :group_enrollments
  resources :group_offerings do
    collection do
      get 'lectures'
      get 'workshops'
      get 'commissions'
      get 'shepperdings'
    end
  end
  resources :child_semesters do
    member do
      delete 'sweet_destroy'
    end
    collection do
      get 'current'
    end
    member do
      get 'receipt'
      put 'pay'
      put 'unpay'
    end
  end
  resources :coordinator_semesters do
    collection do
      get 'current'
    end
  end

  resources :notifications do
    collection do
      get 'read'
      post 'mark_as_read'
    end
  end
  resources :notices do
    collection do
      get 'view'
    end
  end
  resources :users do
    member do
      post 'assign_to_workshop'
      post 'assign_to_shepperding'
      post 'assign_to_lecture'
      post 'assign_to_commission'
      post 'assign_child'
      delete 'unassign_from_workshop'
      delete 'unassign_from_shepperding'
      delete 'unassign_from_lecture'
      delete 'unassign_from_commission'
      delete 'unassign_child'
      post 'assign_child'
      delete 'unassign_child'
      delete 'unshare_task'
      post 'toggle_sidebar'
      post 'add_email'
      post 'add_phone'
      get 'edit_tutor'
      get 'edit_coordinator'
      get 'show_tutor'
      get 'show_coordinator'
    end
    collection do
      get 'tutors'
      get 'coordinators'
      get 'new_coordinator'
      get 'new_tutor'
      get 'typeaheaddata'
      get 'profile'
      patch 'update_password'
      patch 'update_profile'
    end
  end
  resources :emails
  resources :phones
  resources :events do
    collection do
      get 'edit_all'
    end
  end
  resources :workshops do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
      post 'enroll_child'
      delete 'unenroll_child'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :lectures do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
      post 'enroll_child'
      delete 'unenroll_child'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :children do
    member do
      post 'assign_to_tutor'
      delete 'unassign_from_tutor'
      post 'enroll_in_workshop'
      post 'enroll_in_lecture'
      post 'enroll_in_shepperding'
      delete 'unenroll_from_workshop'
      delete 'unenroll_from_lecture'
      delete 'unenroll_from_shepperding'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :visitor_messages
  resources :shepperdings do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
      post 'enroll_child'
      delete 'unenroll_child'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :commissions do
    member do
      post 'assign_coordinator'
      delete 'unassign_coordinator'
    end
    collection do
      get 'typeaheaddata'
    end
  end
  resources :tasks do
    member do
      post 'assign_to_coordinator'
      delete 'unassign_from_coordinator'
      post 'share_to_coordinator'
      post 'mark_as_completed'
      delete 'unmark_as_completed'
    end
  end
  resources :projects do
    member do
      post 'assign_to_coordinator'
      delete 'unassign_from_coordinator'
      post 'share_to_coordinator'
      post 'mark_as_completed'
      delete 'unmark_as_completed'
    end
  end

end

app/views/layouts/partials/_alerts.html.erb
<% if notice or alert %>
	<div class='alert alert-<%= notice ? 'info' : 'warning' %> alert-dismissable'><button class="close" aria-hidden="true" data-dismiss="alert" type="button">&times;</button><%= notice ? notice : alert %></div>
<% end %>

app/views/layouts/partials/_control_sidebar.html.erb
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-clock-o"></i></a></li>
    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-folder-open-o"></i></a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div data-behavior='activity-stream' class="tab-pane active" id="control-sidebar-home-tab">
      <h3 class='control-sidebar-heading'>Actividad reciente</h3>
      <ul class='control-sidebar-menu' data-behavior='activity-stream-items'>
        <% Notification.where( recipient: current_user ).latest.each do |notif| %>
          <li>
            <a href='<%= eval("#{notif.notifiable.class.to_s.pluralize.downcase}_path( anchor: dom_id( notif.notifiable ) )") %>'>
              <i class="menu-icon <%= "#{ notif.human_notifiable[:icon] } bg-#{ notif.human_notifiable[:color] }" %>"></i>
              <div class='menu-info'>
                <h4 class='control-sidebar-subheading'><%= notif.actor.full_name %></h4>
                <p><%= notif.action %> <%= notif.human_notifiable[:text] %></p>
                <p><%= human_date notif.created_at %></p>
              </div>
            </a>
          </li>
        <% end %>
      </ul>
    </div><!-- /.tab-pane -->

    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <h3 class="control-sidebar-heading">Sitios recientes</h3>
      <ul class='control-sidebar-menu'>
        <% RecentItem.latest.where( visitor: current_user ).each do |recenti| %>
          <li>
            <a href='<%= eval( "#{ recenti.recentable.class.to_s.downcase }_path( recenti.recentable )" ) %>'>
              <i class='menu-icon <%= "#{ recenti.human_recentable[:icon] } bg-#{ recenti.human_recentable[:color] }" %>'></i>
              <div class='menu-info'>
                <h4 class='control-sidebar-subheading'><%= recenti.human_recentable[:text] %></h4>
                <p><%= human_date recenti.created_at %></p>
              </div>
            </a>
        <% end %>
    </div><!-- /.tab-pane -->
  </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

app/views/layouts/partials/_header.html.erb
<header class='main-header'>
	<%
		# Logo
	%>
	<a href='<%= dashboard_path %>' class='logo'>
		<%
			# Mini logo for sidebar mini 50 x 50 pixels
		%>
		<span class='logo-mini'><%= image_tag 'tic_logo_nobg_flat.png', height: '40' %></span>
		<%
			# Logo for regular state and mobile devices 
		%>
		<span class='logo-lg'><%= image_tag 'tic_logo_nobg_flat.png', height: '40' %>ticnsp.org</span>
	</a>

	<%
		# Header Navbar
	%>
	<nav class='navbar navbar-static-top' role='navigation'>
		<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button" onclick='toggleUserSidebar(<%= current_user.id %>)'>
	      	<span class="sr-only">Toggle navigation</span>
		</a>
		<%
			# Right menu
		%>
		<div class='navbar-custom-menu'>
			<ul class='nav navbar-nav'>
				<%
					# Mensajes
				%>

				<% render 'layouts/partials/messages' %>

				<%
					# Notifications
				%>
	            <%= render 'layouts/partials/notifications' %>

	            <%
	            	# Tasks menu
	            %>

	            <% render 'layouts/partials/tasks' %>

				<%
					# User account menu
				%>
				<li class='dropdown user user-menu'>
					<a href='#' class='dropdown-toggle' data-toggle='dropdown'>
						<%= image_tag current_user.current_image(40), class: 'user-image', alt: 'User Image' %>
						<span class='hidden-xs'><%= current_user.full_name %></span>
					</a>
					<ul class='dropdown-menu'>
						<%
							# User menu
						%>
						<li class='user-header'>
							<%= image_tag current_user.current_image(80), class: 'img-circle', alt:'User Image' %>
							<p>
								<%= current_user.full_name %>
								<small><%= user_type_display current_user.usertype %></small>
							</p>
						</li>
						<% if false %>
							<li class='user-body'>
								<div class="col-xs-4 text-center">
			            <a href="#">Followers</a>
			          </div>
			          <div class="col-xs-4 text-center">
			            <a href="#">Sales</a>
			          </div>
			          <div class="col-xs-4 text-center">
			            <a href="#">Friends</a>
			          </div>
							</li>
						<% end %>
						<li class='user-footer'>
							<div class="pull-left">
		            <%= link_to 'Perfil', profile_users_path, class: 'btn btn-default btn-flat' %>
		          </div>
		          <div class="pull-right">
		            <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat' %>
		          </div>
						</li>
					</ul>
				</li>
				<%
					# Control sidebar toggle
				%>
        <% if current_user.usertype =~ /admin|coordinator$/ %>
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-send-o"></i></a>
          </li>
        <% end %>
			</ul>
		</div>
	</nav>
</header>

app/views/layouts/partials/_main_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">

    <%
      # Sidebar user panel (optional)
    %>
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag current_user.current_image(80), class: 'img-circle', alt: 'User Image' %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.full_name %></p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <%
      # search form (Optional)
    %>
    <% if false %>
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Buscar..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
          </span>
        </div>
      </form>
    <% end %>

    <%
      # Sidebar Menu
    %>
    <ul class="sidebar-menu">
      <li class="header">MENU</li>

      <li class='<%= params['action'] =~ /dashboard/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-dashboard'></i> <span>Dashboard</span>".html_safe, root_path %></li>

      <li class='<%= params['action'] =~ /evangelio/ ? 'active' : '' %>'><%= link_to "<i class='ion ion-ios-bookmarks'></i> <span>Evangelio</span>".html_safe, evangelio_path %></li>

      <li class='<%= params['controller'] =~ /notices/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-comment'></i> <span>Avisos</span>".html_safe, notices_path %></li>

      <% if current_user.usertype =~ /admin|coordinator$/ %>

        <li class='<%= params['controller'] =~ /visitor_messages/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-inbox'></i> <span>Mensajes</span>".html_safe, visitor_messages_path %></li>

        <% if false %>
        <li class='<%= params['controller'] =~ /tasks/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-tasks'></i> <span>Actividades</span>".html_safe, '#' %></li>

        <% end %>
        <li class='<%= params['controller'] =~ /events/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-calendar'></i> <span>Calendario</span>".html_safe, events_path %></li>

        <li class="header">ADMINISTRACIÓN DE CURSO</li>

            <li class='<%= params['controller'] =~ /child_semesters/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-child'></i> <span>Niños inscritos</span>".html_safe, child_semesters_path %></li>

            <li class='<%= params['controller'] =~ /coordinator_semesters/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-users'></i> <span>Coordinadores</span>".html_safe, coordinator_semesters_path %></li>

            <li class='<%= params['controller'] =~ /tutors/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-users'></i> <span>Tutores</span>".html_safe, tutors_users_path %></li>

            <li class='<%= params['controller'] =~ /group_offerings/ && params['action'] =~ /lectures/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-institution'></i> <span>Catequesis</span>".html_safe, lectures_group_offerings_path %></li>

            <li class='<%= params['controller'] =~ /group_offerings/ && params['action'] =~ /workshops/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-graduation-cap'></i> <span>Talleres</span>".html_safe, workshops_group_offerings_path %></li>

            <li class='<%= params['controller'] =~ /group_offerings/ && params['action'] =~ /shepperdings/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-flag'></i> <span>Acompañamientos</span>".html_safe, shepperdings_group_offerings_path %></li>

            <li class='<%= params['controller'] =~ /group_offerings/ && params['action'] =~ /commissions/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-flag'></i> <span>Comisiones</span>".html_safe, commissions_group_offerings_path %></li>

        <li class='header'>ADMINISTRACIÓN DE SISTEMA</li>

        <li class="treeview">
          <a href="#"><i class='fa fa-gears'></i> <span>Sistema</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li class-'<%= params['controller'] =~ /semesters/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-calendar'></i> <span>Semestres</span>".html_safe, semesters_path %></li>

            <li class='<%= params['controller'] =~ /children/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-child'></i> <span>Niños</span>".html_safe, children_path %></li>

            <li class='<%= params['controller'] =~ /coordinators/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-users'></i> <span>Coordinadores</span>".html_safe, coordinators_users_path %></li>

            <li class='<%= params['controller'] =~ /tutors/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-users'></i> <span>Tutores</span>".html_safe, tutors_users_path %></li>

            <li class='<%= params['controller'] =~ /lectures/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-institution'></i> <span>Catequesis</span>".html_safe, lectures_path %></li>

            <li class='<%= params['controller'] =~ /workshops/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-graduation-cap'></i> <span>Talleres</span>".html_safe, workshops_path %></li>

            <li class='<%= params['controller'] =~ /shepperdings/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-flag'></i> <span>Acompañamientos</span>".html_safe, shepperdings_path %></li>

            <li class='<%= params['controller'] =~ /commissions/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-flag'></i> <span>Comisiones</span>".html_safe, commissions_path %></li>
          </ul>
        </li>

      <% elsif current_user.usertype =~ /tutor/ %>
        <li class='<%= params['action'] =~ /staff/ ? 'active' : '' %>'><%= link_to "<i class='fa fa-group'></i> <span>Coordinación</span>".html_safe, staff_path %></li>
      <% end %>
    </ul>
  </section>

</aside>

app/views/layouts/partials/_messages.html.erb
<li class='dropdown messages-menu'>
  <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
    <i class='fa fa-envelope-o'></i>
    <span class='label label-success'>4</span>
  </a>
  <ul class='dropdown-menu'>
    <%
      # New messages headline
    %>
    <li class='header'>Hay 4 mensajes nuevos</li>
    <li>
      <ul class='menu'>
        <%
          # List of messages
        %>
        <li>
          <a href="#">
            <div class="pull-left">
              <%= image_tag 'coord_ric.jpg', class: 'img-circle', alt:'User Image' %>
            </div>
            
            <h4>
              Support Team
              <small><i class="fa fa-clock-o"></i> 5 mins</small>
            </h4>

            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
      </ul>
    </li>
  </ul>
</li>

app/views/layouts/partials/_notifications.html.erb
<li class="dropdown notifications-menu" data-behavior='notifications'>
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-behavior='notification-link'>
  	<i class="fa fa-bell-o"></i>
  	<span data-behavior='notification-unreadcount' class="label label-warning"></span>
  </a>
  <ul class="dropdown-menu">
  	<li id='notifications-header' class="header" data-behavior='notification-header'></li>
  	<li>
     	<ul id='notifications-menu' class="menu" data-behavior='notification-items'>
      		<%
       			# List of notifications
       		%>
     	</ul>
   	</li>
    <li class="footer"><a href="#">Ver todas</a></li>
  </ul>
</li>

app/views/layouts/partials/_tasks.html.erb
<li class="dropdown tasks-menu">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
  	<i class="fa fa-flag-o"></i>
  	<span class="label label-danger">9</span>
  </a>
  <ul class="dropdown-menu">
  	<li class="header">You have 9 tasks</li>
  	<li>
      	<ul class="menu">
      		<%
    				# List of tasks
    			%>
        		<li>
                  <a href="#">
                    <!-- Task title and progress text -->
                  	<h3>
                      	Design some buttons
                      	<small class="pull-right">20%</small>
                    	</h3>
                    
                    	<div class="progress xs">
                      	<!-- Change the css width attribute to simulate progress -->
                          <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          	<span class="sr-only">20% Complete</span>
                          </div>
                    	</div>
                  </a>
        		</li>

      	</ul>
    	</li>
    	<li class="footer">
      	<a href="#">View all tasks</a>
    	</li>
  </ul>
</li>